### PR TITLE
chore(lib): better log messages

### PR DESCRIPTION
**Pull request by Brijeshthummar02**
issue #78

### CODE REVIEW

**Comment by jeertmans** [comment]
Looks good, thanks! I think some improvements can still be done on other messages, but I don't mind small PRs :-)

Do you want me to wait to October 1st before I merge, for Hacktoberfest?

**Comment by Brijeshthummar02** [comment]
@jeertmans yes please wait for hacktoberfest after that you can merge it.

**Comment by jeertmans** [comment]
Ok! Anyway, CI tests are failing, please see checks above and apply appropriate fixes :-)

**Comment by jeertmans** [comment]
Hey @Brijeshthummar02, I just you just broke the CI (see checks), can you fix it back?

**Pull request closed without merging**
